### ISSUE TITLE
jpgs messed up when running more than 1 webcam.py at once

### ISSUE THREAD

**Issue by mnemocron** [mbjd/WebcamTimelapse#1]
I got some unexpected results when running two `webcam.py` scripts at once like this:
`nohup python webcam.py 10 4h folder01 http://some-ip-01/axis-cgi/jpg/image.cgi &`
`nohup python webcam.py 10 4h folder02 http://some-ip-02/axis-cgi/jpg/image.cgi &`

Both folders were created and filled with images, but not all of 'em are corresponding to their camera origin. (In folder01 contains images of some-ip-02 and vice versa.
The generated videos are made up of the images of both cameras. It appears to alternate the cameras after each picture (the video looks like both video feeds overlapped).

```
$ ls -la
total 116
drwxr-xr-x 5      4096 May 23 18:39 . 
drwxr-xr-x 6      4096 May 23 18:39 ..
drwxr-xr-x 2     57344 May 23 16:33 folder01
-rw-r--r-- 1   7149233 May 23 19:27 folder01.mp4
drwxr-xr-x 2     32768 May 23 15:11 folder02
-rw-r--r-- 1   4304181 May 23 19:27 folder02.mp4
drwxr-xr-x 8      4096 May  6 17:50 .git
-rw-r--r-- 1      1131 May  6 17:50 README.md
-rw-r--r-- 1       728 May 23 17:15 video.py
-rwxr-xr-x 1      3721 May  6 17:50 webcam.py
```

Running on a Linux machine
`Description:    Debian GNU/Linux 8.4 (jessie)`
with Python
`2.7.9 (default, Mar  1 2015, 12:57:24) [GCC 4.9.2]`

**Comment by mbjd** [comment]
Fixed by commit 19b0deb3c5b32ebfeb67fe37483fe90fbcb461dc. The problem was that the image was saved like this:
- os.chdir to target directory
- download image (which takes some time)
- save image in current working directory = target directory
- os.chdir back to original working directory

While one instance of the script was still downloading an image, the other instance called os.chdir to its directory, leading to the image of script instance #1 being saved in the folder created by script instance #2.

Now I've changed it to save directly to the target directory without changing the working directory, and images get to the right folder even when two scripts run asynchronously.
